import { useState } from "react";
import { Plus, X } from "lucide-react";
import { SOURCES, testimonyFor } from "./data";
import { Chapter, SiteNav, SourcesProvider } from "./ui";
import {
  TestimonyFeed,
  type StanceFilter,
  type TypeFilter,
} from "./feed/TestimonyFeed";

/**
 * The testimony feed, on its own.
 *
 * Lifted out of a larger ballot-question page so the feed can be looked at and
 * worked on without eight other sections around it. The filters are held here
 * rather than inside the feed because on the original page other components
 * set them too; here nothing else does, and the wiring is kept so the two stay
 * comparable.
 */
const DISCLAIMER = (
  <p className="font-body text-xs sm:text-sm text-caution-ink leading-[1.5]">
    Prototype for demo purposes only. All content displayed on this page was
    either generated by AI (for individuals) or gathered from published
    statements in public outlets (for orgs and gov officials) for MA 2026
    Q5.
  </p>
);

export default function App({
  positionRow = "inline",
}: {
  /** Where the feed's position picker sits. See TestimonyFeed. */
  positionRow?: "inline" | "below" | "below-labeled" | "responsive";
}) {
  const [stance, setStance] = useState<StanceFilter>("all");
  const [accountType, setAccountType] = useState<TypeFilter>("all");
  // A counter rather than a boolean: the button can ask for the composer again
  // after it has been closed, which a boolean would swallow.
  const [composeSignal, setComposeSignal] = useState(0);
  // Dismissing the notice hides it for the rest of the visit; it comes back
  // on the next page load.
  const [showNotice, setShowNotice] = useState(true);
  // The close button floats in the top-right corner, so only the first line
  // of the note makes room for it and the rest run the full width.
  const notice = (
    <div className="flow-root">
      {/* Padded for a thumb, with the padding pulled back out of the layout. */}
      <button
        onClick={() => setShowNotice(false)}
        aria-label="Dismiss notice"
        className="float-right ml-[8px] -m-[8px] p-[8px] text-caution-ink hover:opacity-70 cursor-pointer"
      >
        <X className="size-[16px]" />
      </button>
      {DISCLAIMER}
    </div>
  );

  return (
    <SourcesProvider value={SOURCES}>
      <div className="bg-ground min-h-screen font-body text-ink overflow-x-clip">
        {showNotice && (
          <div className="sm:hidden bg-caution-soft border-b border-caution-ink/28 px-[20px] py-[8px]">
            {notice}
          </div>
        )}
        <SiteNav />
        {/* Below lg the nav is pinned, so the feed's sticky filter bar sticks
            under it: the nav's height plus its 1px bottom rule. From lg up
            nothing is pinned above the feed and the bar sticks to the top of
            the window. */}
        <main className="mx-auto max-w-[1180px] px-[20px] sm:px-[32px] pt-[20px] sm:pt-[32px] pb-[140px] [--pinned-h:calc(var(--nav-h)_+_1px)] lg:[--pinned-h:0px]">
          <Chapter
            id="testimony"
            question="What is the public saying?"
            fullWidth
          >
            <TestimonyFeed
              filter={stance}
              onFilterChange={setStance}
              typeFilter={accountType}
              onTypeFilterChange={setAccountType}
              hideAddButton
              composeSignal={composeSignal}
              items={testimonyFor(() => true)}
              stickyTop="var(--pinned-h)"
              includeFollowingFilter
              positionRow={positionRow}
              compactHeaderNarrow
              includeTypeFilter
              asCards
            />
          </Chapter>
        </main>
        {/* A circle at rest that opens into its own label on hover. The width
            animates through `grid-template-columns`, from 0fr to 1fr, rather
            than through max-width: a max-width has to guess a ceiling and then
            spends most of the duration animating empty space past the end of
            the text. Sits above the sticky note, not over it. */}
        <button
          onClick={() => setComposeSignal((n) => n + 1)}
          aria-label="Add your perspective"
          className={`group fixed bottom-[24px] ${
            showNotice ? "sm:bottom-[76px]" : ""
          } right-[24px] z-50 inline-flex items-center h-[52px] pl-[16px] pr-[16px] rounded-pill border border-brand bg-brand text-ink-inverse shadow-panel hover:bg-brand-hover hover:border-brand-hover cursor-pointer transition-colors`}
        >
          <Plus className="w-[22px] h-[22px] shrink-0" />
          <span className="grid grid-cols-[0fr] group-hover:grid-cols-[1fr] group-focus-visible:grid-cols-[1fr] transition-[grid-template-columns] duration-300 ease-out motion-reduce:transition-none">
            <span className="overflow-hidden">
              <span className="block pl-[10px] pr-[2px] font-body font-semibold text-sm whitespace-nowrap">
                Add your perspective
              </span>
            </span>
          </span>
        </button>

        {/* From sm up, pinned to the bottom: the note has to be visible without
            being the first thing on the page, and a footer that scrolls away is
            a note most readers never reach. On phones it sits at the top
            instead, where it scrolls away rather than covering the feed. */}
        {showNotice && (
          <footer className="hidden sm:block fixed bottom-0 left-0 right-0 z-40 bg-caution-soft border-t border-caution-ink/28">
            {/* Parked: the band above the bar, 8px of solid ground and 48px of
                fade, so content dissolved rather than cutting at the border.
            <div
              aria-hidden
              className="pointer-events-none absolute bottom-[calc(100%+1px)] left-0 right-0 h-[56px] bg-gradient-to-t from-ground from-14% via-ground/80 via-57% to-transparent"
            />
            */}
            <div className="px-[20px] sm:px-[32px] py-[10px]">{notice}</div>
          </footer>
        )}
      </div>
    </SourcesProvider>
  );
}
